# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes :boom:
      labels:
        - breaking-change
    - title: Bug Fix :construction:
      labels:
        - bug
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
